In [6]:
#all the imports needed for the project
import struct
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
import os

The MNIST data needs to be read into a pandas database first before continuing 
with the Neural Network. 

In [13]:
data = pd.read_csv('/Users/armaansidhu/Documents/Code/MNIST-Neural-Network/mnist_train.csv')

Next steps include converting the dataframe into numpy array, shuffling the data, then splitting the data into training and test

In [29]:
data = np.array(data, copy = True)
m, n = data.shape
np.random.shuffle(data) #shuffling the data

data_train = data.T
Y_train = data_train[0]
X_train = data_train[1:n]
X_train = X_train / 255.

In [22]:
def init_params():
    "initialising the weight matrices and the bias vectors"

    W1 = np.random.rand(10,784) - 0.5
    b1 = np.random.rand(10, 1) - 0.5
    W2 = np.random.rand(10, 10) - 0.5
    b2 = np.random.rand(10, 1) - 0.5
    return W1, b1, W2, b2

def ReLu(Z):
    "introduces non linear relationships into the model so that the model"
    "can learn non linear relationship"
    "reduces the vanishing gradient problem"

    return np.maximum(0, Z)

def softmax(Z):
    "gets the probability of each neuron in the output layer, all probablities"
    "add to 1"
    "digit with the highest probability is then picked"

    A = np.exp(Z)/sum(np.exp(Z))
    return A

def forward_propagation(W1, b1, W2, b2, X):
    "Forward pass of the neural network"

    Z1 = W1.dot(X) + b1             # First hidden layer linear transformation
    A1 = ReLu(Z1)                   # Adds Non linearity to the model
    Z2 = W2.dot(A1) + b2            # Linear transforamtion for output layer
    A2 = softmax(Z2)                # getting probability for each output neuron
    return Z1, A1, Z2, A2


def ReLu_deriv(Z):
    "Used in back propagation"

    return Z > 0                    # Returns an array of 1 and 0

def one_hot(Y):
    "Creates and array where it is all zeroes and 1 in the index of the correct"
    "digit"

    one_hot_Y = np.zeros((Y.size, Y.max() + 1))      # zeros array, right size
    one_hot_Y[np.arange(Y.size), Y] = 1             # selects the correct index
    one_hot_Y = one_hot_Y.T                          # transposes
    return one_hot_Y

def backward_propagation(Z1, A1, Z2, A2, W1, W2, X, Y):
    "backwards pass of the neural network"
    "calculates the gradients of the weights and biases so that they can be"
    "updated"

    one_hot_Y = one_hot(Y)   # convert to one hot matrix
    dZ2 = A2 - one_hot_Y   # gradient loss of Z2
    dW2 = 1 / m * dZ2.dot(A1.T)   # Weight gradient for second layer
    db2 = 1 / m * np.sum(dZ2)   # bias gradient for second layer
    dZ1 = W2.T.dot(dZ2) * ReLu_deriv(Z1)   # Back propagate error into first layer
    dW1 = 1 / m * dZ1.dot(X.T)   # weight gradient for first layer
    db1 = 1 / m * np.sum(dZ1)   # bias gradient for first layer
    return dW1, db1, dW2, db2

def update_params(W1, b1, W2, b2, dW1, db1, dW2, db2, alpha):
    "Updating the wieght and biases according to the back propagation func"

    W1 = W1 - alpha * dW1
    b1 = b1 - alpha * db1    
    W2 = W2 - alpha * dW2  
    b2 = b2 - alpha * db2    
    return W1, b1, W2, b2

In [23]:
def get_predictions(A2):
    return np.argmax(A2, 0)

def get_accuracy(predications, Y):
    print(predications, Y)
    return  np.sum(predications == Y) / Y.size

def gradient_descent(X, Y, alpha, iterations):
    W1, b1, W2, b2 = init_params()
    for i in range(iterations):
        Z1, A1, Z2, A2 = forward_propagation(W1, b1, W2, b2, X)
        dW1, db1, dW2, db2 = backward_propagation(Z1, A1, Z2, A2, W1, W2, X, Y)
        W1, b1, W2, b2 = update_params(W1, b1, W2, b2, dW1, db1, dW2, db2, alpha)
        if i % 10 == 0:
            print("Iteration: ", i)
            predictions = get_predictions(A2)
            print(get_accuracy(predictions, Y))
    return W1, b1, W2, b2


In [31]:
W1, b1, W2, b2 = gradient_descent(X_train, Y_train, 0.10, 500)

Iteration:  0
[5 1 5 ... 8 3 5] [9 0 7 ... 9 1 8]
0.070801180019667
Iteration:  10
[6 1 3 ... 9 3 9] [9 0 7 ... 9 1 8]
0.17950299171652861
Iteration:  20
[7 6 3 ... 9 9 9] [9 0 7 ... 9 1 8]
0.27843797396623277
Iteration:  30
[7 0 7 ... 9 9 9] [9 0 7 ... 9 1 8]
0.3388889814830247
Iteration:  40
[7 0 7 ... 9 9 9] [9 0 7 ... 9 1 8]
0.38768979482991384
Iteration:  50
[7 0 7 ... 9 9 9] [9 0 7 ... 9 1 8]
0.4354072567876131
Iteration:  60
[7 0 7 ... 9 3 9] [9 0 7 ... 9 1 8]
0.4788413140219004
Iteration:  70
[7 0 7 ... 9 3 9] [9 0 7 ... 9 1 8]
0.5175586259770997
Iteration:  80
[7 0 7 ... 9 3 9] [9 0 7 ... 9 1 8]
0.5521758695978266
Iteration:  90
[7 0 7 ... 9 3 9] [9 0 7 ... 9 1 8]
0.5853264221070351
Iteration:  100
[7 0 7 ... 9 3 9] [9 0 7 ... 9 1 8]
0.6170769512825214
Iteration:  110
[7 0 7 ... 9 1 9] [9 0 7 ... 9 1 8]
0.6427607126785446
Iteration:  120
[7 0 7 ... 9 1 9] [9 0 7 ... 9 1 8]
0.6642777379622994
Iteration:  130
[7 0 7 ... 9 1 9] [9 0 7 ... 9 1 8]
0.6842780713011883
Iteration:  140